[package]
org = "ballerina"
name = "log"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["level", "format"]
repository = "https://github.com/ballerina-platform/module-ballerina-log"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-native"
version = "@toml.version@"
path = "../native/build/libs/log-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-compiler-plugin"
version = "@toml.version@"
path = "../compiler-plugin/build/libs/log-compiler-plugin-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-test-utils"
version = "@toml.version@"
path = "../test-utils/build/libs/log-test-utils-@project.version@.jar"
scope = "testOnly"
