[package]
org = "ballerina"
name = "log"
version = "2.2.0"
authors = ["Ballerina"]
keywords = ["level", "format"]
repository = "https://github.com/ballerina-platform/module-ballerina-log"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/log-native-2.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/log-test-utils-2.2.0-SNAPSHOT.jar"
