[package]
org = "ballerina"
name = "log"
version = "2.4.1"
authors = ["Ballerina"]
keywords = ["level", "format"]
repository = "https://github.com/ballerina-platform/module-ballerina-log"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-native"
version = "2.4.1"
path = "../native/build/libs/log-native-2.4.1.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-test-utils"
version = "2.4.1"
path = "../test-utils/build/libs/log-test-utils-2.4.1.jar"
scope = "testOnly"
