[package]
org = "ballerina"
name = "log"
version = "2.15.0"
authors = ["Ballerina"]
keywords = ["level", "format"]
repository = "https://github.com/ballerina-platform/module-ballerina-log"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-native"
version = "2.15.0"
path = "../native/build/libs/log-native-2.15.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-compiler-plugin"
version = "2.15.0"
path = "../compiler-plugin/build/libs/log-compiler-plugin-2.15.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-test-utils"
version = "2.15.0"
path = "../test-utils/build/libs/log-test-utils-2.15.0.jar"
scope = "testOnly"
